from __future__ import annotations

import time
from dataclasses import dataclass
from typing import Any

import numpy as np
from scipy.optimize import least_squares

from quasi_exp.model.tension_transmission import transmit_tensions


@dataclass(frozen=True)
class SegmentedTensionResult:
    T_base_12: np.ndarray
    mean_rnorm2: float
    rms_rnorm: float
    max_tension: float
    section_rms_rnorm: dict[str, float]
    section_elapsed_s: dict[str, float]
    section_nfev: dict[str, int]
    success: bool
    elapsed_s: float
    message: str


@dataclass(frozen=True)
class _Stage:
    name: str
    cable_indices: np.ndarray
    boundary_i: int
    residual_slice: slice


_STAGES: tuple[_Stage, ...] = (
    _Stage("third", np.array([4, 5, 6, 7], dtype=int), 20, slice(20, 30)),
    _Stage("second", np.array([2, 3, 8, 9], dtype=int), 10, slice(10, 20)),
    _Stage("first", np.array([0, 1, 10, 11], dtype=int), 0, slice(0, 10)),
)


def unit_transmission_factors(model, cache) -> np.ndarray:
    """Return F_CT generated by unit base tension for the current theta."""
    F_unit, _case = transmit_tensions(
        theta_rad=cache.theta_rad,
        T_base_12=np.ones(12, dtype=float),
        mu_cable=float(model.mu_cable),
        end_disk_by_j=model.end_disk_by_j,
        L0_12=model.L0_12,
        L_12=cache.L_12,
    )
    return np.asarray(F_unit, dtype=float)


def boundary_tensions_to_base(
    boundary_tensions: np.ndarray,
    unit_factors: np.ndarray,
    *,
    boundary_i: int,
    cable_indices: np.ndarray,
    t_min: float,
    t_max: float,
    base_template: np.ndarray | None = None,
) -> np.ndarray:
    """
    Convert segment-boundary tensions to base tensions using Eq.(42) unit factors.

    If unit_factors[boundary_i, j] is the tension at boundary_i generated by
    base tension 1 N, then base_tension_j = boundary_tension_j / factor.
    """
    unit = np.asarray(unit_factors, dtype=float)
    cables = np.asarray(cable_indices, dtype=int).reshape(-1)
    x = np.asarray(boundary_tensions, dtype=float).reshape(cables.shape[0])
    if unit.ndim != 2 or unit.shape[1] != 12:
        raise ValueError(f"unit_factors must have shape (kD+1, 12), got {unit.shape}")
    if int(boundary_i) < 0 or int(boundary_i) >= unit.shape[0]:
        raise ValueError(f"boundary_i out of range: {boundary_i}")

    if base_template is None:
        base = np.zeros(12, dtype=float)
    else:
        base = np.asarray(base_template, dtype=float).reshape(12).copy()

    factors = unit[int(boundary_i), cables]
    if (not np.isfinite(factors).all()) or np.any(factors <= 1e-12):
        raise ValueError(f"invalid unit transmission factors at boundary_i={boundary_i}: {factors}")

    base[cables] = x / factors
    return np.clip(base, float(t_min), float(t_max))


def _rms(values: np.ndarray) -> float:
    arr = np.asarray(values, dtype=float).reshape(-1)
    if arr.size == 0 or not np.isfinite(arr).all():
        return float("inf")
    return float(np.sqrt(np.mean(np.square(arr))))


def _residual_vector(
    model,
    cache,
    T_base: np.ndarray,
    residual_slice: slice,
    residual_weight: float,
) -> np.ndarray:
    rnorm, _debug = model.residual_norm(cache, T_base)
    vec = np.asarray(rnorm[residual_slice], dtype=float) * float(residual_weight)
    return np.nan_to_num(vec, nan=1.0e9, posinf=1.0e9, neginf=-1.0e9)


def solve_tensions_segmented(
    model,
    cache,
    solver_cfg: dict[str, Any] | None = None,
) -> SegmentedTensionResult:
    """
    Deterministic distal-to-proximal segmented tension solve.

    This is a diagnostic allocator: it reuses the current Eq.(42) forward
    transmission and converts segment boundary variables back to base tensions.
    It does not yet implement a separate reverse friction law.
    """
    cfg = dict(solver_cfg or {})
    t_min = float(model.t_min)
    t_max = float(model.t_max)
    if t_max <= t_min:
        raise ValueError(f"invalid tension bounds: [{t_min}, {t_max}]")

    max_nfev = max(1, int(cfg.get("max_nfev", 80)))
    residual_weight = float(cfg.get("residual_weight", 1.0))
    w_ref = max(0.0, float(cfg.get("w_ref", 0.02)))
    w_base_norm = max(0.0, float(cfg.get("w_base_norm", 0.005)))
    w_anchor = max(0.0, float(cfg.get("w_anchor", 0.0)))
    feasible_rms = float(cfg.get("feasible_rms_rnorm", 0.06))
    t_ref = float(cfg.get("t_ref_n", 0.4 * t_max))
    t_ref = float(np.clip(t_ref, t_min, t_max))
    anchor_raw = cfg.get("anchor_tension_n")
    T_anchor = None
    if anchor_raw is not None:
        T_anchor = np.clip(np.asarray(anchor_raw, dtype=float).reshape(12), t_min, t_max)
        if not np.isfinite(T_anchor).all():
            raise ValueError("segmented_tension.anchor_tension_n must be finite")

    unit = unit_transmission_factors(model, cache)
    T_base = T_anchor.copy() if T_anchor is not None else np.ones(12, dtype=float) * t_ref
    T_base = np.clip(T_base, t_min, t_max)

    section_rms: dict[str, float] = {}
    section_elapsed: dict[str, float] = {}
    section_nfev: dict[str, int] = {}
    messages: list[str] = []
    optimizers_success = True
    t0_all = time.perf_counter()

    for stage in _STAGES:
        stage_t0 = time.perf_counter()
        cables = stage.cable_indices
        factors = unit[stage.boundary_i, cables]
        if (not np.isfinite(factors).all()) or np.any(factors <= 1e-12):
            raise ValueError(f"invalid factors for stage={stage.name}: {factors}")

        lower = np.asarray(t_min * factors, dtype=float)
        upper = np.asarray(t_max * factors, dtype=float)
        x0 = np.clip(T_base[cables] * factors, lower, upper)
        x_ref = np.clip(t_ref * factors, lower, upper)
        x_anchor = None
        if T_anchor is not None:
            x_anchor = np.clip(T_anchor[cables] * factors, lower, upper)
        x_denom = np.maximum(np.abs(t_max * factors), 1.0)
        base_denom = max(abs(t_max), 1.0)

        def objective(x: np.ndarray) -> np.ndarray:
            candidate = boundary_tensions_to_base(
                x,
                unit,
                boundary_i=stage.boundary_i,
                cable_indices=cables,
                t_min=t_min,
                t_max=t_max,
                base_template=T_base,
            )
            parts = [_residual_vector(model, cache, candidate, stage.residual_slice, residual_weight)]
            if w_ref > 0.0:
                parts.append(np.sqrt(w_ref) * ((np.asarray(x, dtype=float) - x_ref) / x_denom))
            if w_base_norm > 0.0:
                parts.append(np.sqrt(w_base_norm) * (candidate[cables] / base_denom))
            if w_anchor > 0.0 and x_anchor is not None:
                parts.append(np.sqrt(w_anchor) * ((np.asarray(x, dtype=float) - x_anchor) / x_denom))
            return np.concatenate(parts)

        opt = least_squares(
            objective,
            x0,
            bounds=(lower, upper),
            max_nfev=max_nfev,
            xtol=float(cfg.get("xtol", 1e-8)),
            ftol=float(cfg.get("ftol", 1e-8)),
            gtol=float(cfg.get("gtol", 1e-8)),
            x_scale=np.maximum(np.abs(x_ref), 1.0),
        )
        T_base = boundary_tensions_to_base(
            opt.x,
            unit,
            boundary_i=stage.boundary_i,
            cable_indices=cables,
            t_min=t_min,
            t_max=t_max,
            base_template=T_base,
        )

        rnorm, _debug = model.residual_norm(cache, T_base)
        section_rms[stage.name] = _rms(rnorm[stage.residual_slice])
        section_elapsed[stage.name] = float(time.perf_counter() - stage_t0)
        section_nfev[stage.name] = int(opt.nfev)
        optimizers_success = bool(optimizers_success and opt.success)
        messages.append(f"{stage.name}:{opt.message}")

    final_rnorm, _debug = model.residual_norm(cache, T_base)
    mean_r2 = float(np.mean(np.square(final_rnorm)))
    rms_rnorm = float(np.sqrt(mean_r2))
    success = bool(optimizers_success and np.isfinite(rms_rnorm) and rms_rnorm <= feasible_rms)

    return SegmentedTensionResult(
        T_base_12=T_base.copy(),
        mean_rnorm2=mean_r2,
        rms_rnorm=rms_rnorm,
        max_tension=float(np.max(T_base)),
        section_rms_rnorm=section_rms,
        section_elapsed_s=section_elapsed,
        section_nfev=section_nfev,
        success=success,
        elapsed_s=float(time.perf_counter() - t0_all),
        message=" | ".join(messages),
    )
